version: "3"

services:
  nodeserver:
      build: 
        context: ./server/node/
        dockerfile: Dockerfile
      ports:
        - "2018:2018" #node http port
        - "2019:2019" #node wsocket port
      volumes: 
        - ./server/node:/usr/app
        - /usr/app/node_modules

  pythonserver:
    build: ./server/python/
    ports:
      - "2020:2020"
    volumes:
      - ./server/python:/usr/app
