version: '3'

services:
  node:
      build: ./backend/node/
      ports:
        - "2018:2018" #node http port
        - "2019:2019" #node wsocket port
      volumes: 
        - ./backend/node/:/www/node

  python:
    build: ./backend/python/
    ports:
      - "2020:2020"
    volumes:
      - ./backend/python/:/www/python